version: '3'
services:
  jenkins:
    build: ./jenkinsci
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkinsci/data:/var/jenkins_home
    networks:
      - fabric

networks:
  fabric:
