version: '3'
services:
  weaver:
    image: tomcat:9-jre10-slim
    restart: on-failure
    depends_on:
      - database
    #volumes:
      #  - project-build:/projects-build:ro
    networks:
      - fabric

  jenkins:
    build: ./jenkinsci
    ports:
      - 80:8080
    depends_on:
      - weaver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkinsci/data:/var/jenkins_home
        #- project-build:/var/jenkins_home/workspace
    networks:
      - fabric

  database:
    build: ./database
    restart: on-failure
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: guava
      MYSQL_DATABASE: guava
      MYSQL_USER: guava
      MYSQL_PASSWORD: guava
    networks:
      - fabric

networks:
  fabric:

volumes:
  project-build:
